import {REACTIONS} from './bank.js';
import {makeProblem,solve,eligibleReactions,parseAnswer,closeEnough,checkCoefficients,significantFigures,format,sig,looksLikeEarlyRounding} from './engine.js';
import {chem,number,species,equation,reference,solution,lessonView} from './views.js';
const $=id=>document.getElementById(id);
const TITLES={mass:'Theoretical yield',limiting:'Limiting reactant + yield',percent:'Percent yield'};
let lesson='mass',problem=null,balanced=false,attempted=false,complete=false,revealed=false,attempts=0,solved=0,problemCount=0;
function mode(value){$('learn-view').hidden=value!=='learn';$('practice-view').hidden=value!=='practice';$('learn-tab').setAttribute('aria-pressed',String(value==='learn'));$('practice-tab').setAttribute('aria-pressed',String(value==='practice'));if(value==='practice'&&!problem)newProblem();}
function showLesson(value){lesson=value;$('lesson').innerHTML=lessonView(value);document.querySelectorAll('[data-lesson]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.lesson===value)));$('try-lesson').textContent='Practice '+(value==='mass'?'mass to mass':value==='limiting'?'limiting reactants':'percent yield');}
$('learn-tab').addEventListener('click',()=>mode('learn'));
$('practice-tab').addEventListener('click',()=>mode('practice'));
document.querySelectorAll('[data-lesson]').forEach(b=>b.addEventListener('click',()=>showLesson(b.dataset.lesson)));
$('try-lesson').addEventListener('click',()=>{$('track').value=lesson;refreshReactions();newProblem();mode('practice');$('practice-tab').focus();});
function refreshReactions(){const prior=$('reaction').value,eligible=eligibleReactions($('track').value);$('reaction').innerHTML=`<option value="random">Surprise me · all ${eligible.length}</option>`+eligible.map(r=>`<option value="${r.id}">${String(r.id).padStart(2,'0')} · ${r.name}</option>`).join('');if(eligible.some(r=>String(r.id)===prior))$('reaction').value=prior;}
function newProblem(){problem=makeProblem({track:$('track').value,reactionId:$('reaction').value==='random'?undefined:$('reaction').value,balanceFirst:$('balance-mode').value==='first'});balanced=!problem.balanceFirst;attempted=false;complete=false;revealed=false;problemCount++;renderProblem();}
for(const id of ['track','balance-mode','reaction'])$(id).addEventListener('change',()=>{if(id==='track')refreshReactions();newProblem();});
$('new-problem').addEventListener('click',newProblem);
function score(){ $('score').textContent=`${solved} solved · ${attempts} attempted this visit`; }
function recordAttempt(){if(!attempted){attempted=true;attempts++;score();}}
function balanceMarkup(){const r=problem.reaction;let i=0;const side=ss=>ss.map(s=>`<span class="species"><input class="coefficient" id="coef-${i++}" type="number" min="1" max="99" step="1" inputmode="numeric" aria-label="Coefficient for ${s.formula} ${r.reactants.includes(s)?'reactant':'product'}">${species(s)}</span>`).join('<span class="plus">+</span>');return `<div class="balance-block"><h2>First, balance the equation.</h2><p class="muted">Use the smallest whole-number coefficients. Enter 1 where needed.</p><form id="balance-form"><div class="equation">${side(r.reactants)}<span class="arrow">→</span>${side(r.products)}</div><div id="balance-feedback" class="feedback" role="status"></div><div class="actions"><button class="primary" type="submit">Check balance</button><button type="button" id="show-balance">Show balanced equation</button></div></form></div>`;}
function renderProblem(){const p=problem,product=chem(p.reaction.products[p.target].formula);const more=p.given.length===1?p.reaction.reactants.filter((_,i)=>i!==p.given[0].index):[];
 const fields=`${p.given.length===2?`<fieldset class="field"><legend>Which reactant is limiting?</legend><div class="limiting-choices">${p.reaction.reactants.map((r,i)=>`<label><input type="radio" name="limiting" value="${i}">${chem(r.formula)}</label>`).join('')}</div></fieldset>`:''}<div class="field"><label for="theoretical">Theoretical yield of ${product}</label><div class="input-unit"><input id="theoretical" type="text" inputmode="decimal" autocomplete="off" spellcheck="false" placeholder="Enter mass" aria-describedby="answer-help"><span>g ${product}</span></div><small id="answer-help">All given masses have 3 significant figures. Keep extra digits until the end, then report 3 significant figures. Correct calculations are accepted with a separate rounding tip when needed.<br>You may include g. Use a decimal point or comma (12.6 or 12,6); do not use thousands separators.<br>Scientific notation works: <span class="inline-code">1.25e-3</span>, <span class="inline-code">1.25 × 10^-3</span>, or <span class="inline-code">1.25×10-3</span>.</small></div>${p.track==='percent'?`<div class="field"><label for="percent">Percent yield</label><div class="input-unit"><input id="percent" type="text" inputmode="decimal" autocomplete="off" spellcheck="false" placeholder="Enter percent" aria-describedby="percent-help"><span>%</span></div><small id="percent-help">The % sign is optional. Enter a positive number, such as 87.9 or 87.9%.</small></div>`:''}`;
 $('problem').innerHTML=`<div class="problem-meta"><span>Problem ${problemCount} · ${TITLES[p.track]}</span><span>Reaction ${String(p.reaction.id).padStart(2,'0')} · ${p.reaction.name}</span></div><div class="equation-card"><p class="eyebrow">FIND THE MASS OF ${product}</p><div class="equation" id="current-equation">${equation(p.reaction,balanced)}</div><div class="given-row">${p.given.map(g=>`<div class="given"><small>Starting amount</small><strong>${number(g.mass)} g ${chem(p.reaction.reactants[g.index].formula)}</strong></div>`).join('')}${p.actual!==null?`<div class="given actual"><small>Actual yield collected</small><strong>${number(p.actual)} g ${product}</strong></div>`:''}</div>${more.length?`<p class="context"><strong>${more.map(r=>chem(r.formula)).join(' and ')} is in excess.</strong></p>`:''}<p class="context">${p.reaction.conditions}</p>${[...p.reaction.reactants,...p.reaction.products].some(r=>r.state==='aq')?'<p class="context">For (aq) substances, grams refer to the dissolved substance, not the total solution. Salts use the anhydrous formula shown.</p>':''}</div>${balanced?'':balanceMarkup()}<div class="work-layout"><div class="answer-panel"><div id="answer-feedback" class="feedback" role="status" aria-live="polite"></div><div id="precision-feedback" class="precision-feedback" role="status" hidden></div><form id="answer-form"><fieldset id="answer-fields" ${balanced?'':'disabled'}>${fields}</fieldset><div class="actions"><button id="check-answer" class="primary" type="submit" ${balanced?'':'disabled'}>Check answer</button><button id="hint-button" type="button">Show a hint</button><button id="solution-button" type="button">Show solution</button></div></form><div id="hint" class="hint" hidden></div><section id="solution" class="solution" hidden aria-label="Worked solution"></section><button id="next-problem" class="primary" hidden>Next problem</button></div>${reference(p)}</div>`;
 $('answer-form').addEventListener('submit',event=>{event.preventDefault();checkAnswer();});$('hint-button').addEventListener('click',showHint);$('solution-button').addEventListener('click',revealSolution);$('next-problem').addEventListener('click',()=>{newProblem();$('problem').scrollIntoView({behavior:'auto',block:'start'});});
 if(!balanced){$('balance-form').addEventListener('submit',event=>{event.preventDefault();const values=[...document.querySelectorAll('.coefficient')].map(el=>Number(el.value));const error=checkCoefficients(p.reaction,values);if(error){$('balance-feedback').textContent=error;return;}unlockBalance(false);});$('show-balance').addEventListener('click',()=>unlockBalance(true));}score();
}
function unlockBalance(shown){balanced=true;$('current-equation').innerHTML=equation(problem.reaction);document.querySelector('.balance-block').innerHTML=`<p class="balance-note">${shown?'Balanced equation shown above. Use its coefficients in your mole ratio.':'Balanced correctly. Now use the coefficients to calculate product mass.'}</p>`;$('answer-fields').disabled=false;$('check-answer').disabled=false;}
function checkAnswer(){if(!balanced||complete)return;const theoretical=parseAnswer($('theoretical').value,'g'),percent=problem.track==='percent'?parseAnswer($('percent').value,'%'):null;const selected=document.querySelector('input[name="limiting"]:checked');if(theoretical===null||(problem.track==='percent'&&percent===null)||(problem.given.length===2&&!selected)){feedback('Enter a positive number in every answer box and choose a limiting reactant when asked. Mass answers may end in g; percent answers may end in %. Use one decimal point or comma and no thousands separators.',false);return;}
 recordAttempt();const s=solve(problem),errors=[];const massCorrect=closeEnough(theoretical,s.theoretical);
 if(problem.given.length===2&&Number(selected.value)!==s.limiting)errors.push('Recheck the limiting reactant: calculate the mass of the same product from each starting reactant, then compare.');
 if(!massCorrect){const r=problem.reaction.reactants[problem.given[0].index],product=problem.reaction.products[problem.target];const massRatioMistake=problem.given[0].mass*product.coefficient/r.coefficient;if(closeEnough(theoretical,massRatioMistake))errors.push('The coefficients compare moles, not grams. Convert the starting mass to moles before using the ratio.');else if(problem.given.length===2&&s.paths.some(path=>path.index!==s.limiting&&closeEnough(theoretical,path.yield)))errors.push('That mass comes from the excess reactant. The smaller possible product mass sets the theoretical yield.');else if(looksLikeEarlyRounding(problem,theoretical))errors.push('Your answer matches a calculation rounded between steps. Try again with the full calculator values for both mole conversions; round to 3 significant figures only after finding the final mass.');else errors.push('Recheck the theoretical yield: grams → moles → mole ratio → grams. Use the molar masses listed here and keep extra digits until the final answer.');}
 if(problem.track==='percent'&&!closeEnough(percent,s.percent))errors.push(looksLikeEarlyRounding(problem,percent,'percent')?'Your percent yield matches a calculation rounded too early. Keep the unrounded theoretical yield in actual ÷ theoretical × 100, then round the final percentage to 3 significant figures.':massCorrect?'The theoretical yield is correct. For percent yield, divide actual yield by theoretical yield, then multiply by 100.':'Calculate theoretical yield first, then use actual ÷ theoretical × 100 for percent yield.');
 if(errors.length){feedback(errors.join(' '),false);return;}showPrecisionFeedback(s);complete=true;if(!revealed)solved++;score();feedback(revealed?'These values match the worked solution. Try a new problem to check your understanding.':'Correct. '+(problem.given.length===2?'You identified the limiting reactant and calculated the yield.':'Your mass calculation is correct.')+(problem.track==='percent'?' Your percent yield is correct, too.':''),true);$('check-answer').disabled=true;$('answer-fields').disabled=true;$('solution-button').textContent='View worked solution';$('next-problem').hidden=false;
}
function showPrecisionFeedback(s){
 const entries=[{id:'theoretical',expected:s.theoretical,label:'theoretical yield',unit:'g'}];
 if(problem.track==='percent')entries.push({id:'percent',expected:s.percent,label:'percent yield',unit:'%'});
 const tips=entries.flatMap(entry=>{
   const text=$(entry.id).value,count=significantFigures(text,entry.unit);
   const rounded=sig(entry.expected),value=parseAnswer(text,entry.unit);
   const matchesRounded=Math.abs(value-rounded)<=Math.abs(rounded)*1e-12;
   if(count===3&&matchesRounded)return [];
   const reason=count===null?'The precision of a whole number ending in zero is unclear without a decimal point or scientific notation.':count!==3?`Your entry has ${count} significant figure${count===1?'':'s'}.`:'Keep extra digits in the intermediate steps and round only the final result.';
   return [`For ${entry.label}, report ${format(entry.expected)}${entry.unit==='g'?' g':'%'} (3 significant figures). ${reason}`];
 });
 $('precision-feedback').hidden=tips.length===0;
 $('precision-feedback').textContent=tips.length?'Calculation accepted. Rounding tip: '+tips.join(' '):'';
}
function feedback(message,good){$('answer-feedback').textContent=message;$('answer-feedback').className='feedback'+(good?' success':'');}
function showHint(){$('hint').hidden=!$('hint').hidden;$('hint-button').textContent=$('hint').hidden?'Show a hint':'Hide hint';$('hint').innerHTML=!balanced?'Balance the atoms first. Change only coefficients, never the subscripts in a formula.':problem.given.length===2?'Make two mass-to-mass calculations, one from each reactant. The smaller product mass gives both the limiting reactant and theoretical yield.':problem.track==='percent'?'Calculate the maximum product mass from the starting reactant. Then compare the mass actually collected with that theoretical mass.':'Divide the reactant mass by its molar mass, multiply by the product/reactant coefficient ratio, then multiply by the product molar mass.';}
function revealSolution(){recordAttempt();if(!complete)revealed=true;if(!balanced)unlockBalance(true);$('solution').innerHTML=solution(problem);$('solution').hidden=false;$('next-problem').hidden=false;$('solution-button').disabled=true;if(!complete)feedback('Worked solution shown. You can enter the values to check the steps; this problem will not count as independently solved.',false);}
showLesson('mass');refreshReactions();score();
const context=document.modelContext;
if(context?.registerTool){const lifecycle=new AbortController();const tools=[
 {name:'read_stoichiometry_problem',description:'Read the visible problem, given masses, track and completion status. Does not reveal answers.',annotations:{readOnlyHint:true,untrustedContentHint:false},inputSchema:{type:'object',properties:{},additionalProperties:false},execute:()=>({mode:$('practice-view').hidden?'learn':'practice',problem:problem?{reactionId:problem.reaction.id,track:problem.track,target:problem.reaction.products[problem.target].formula,given:problem.given.map(g=>({formula:problem.reaction.reactants[g.index].formula,massGrams:g.mass})),actualYieldGrams:problem.actual,balanced,complete,solutionRevealed:revealed}:null})},
 {name:'start_stoichiometry_problem',description:'Start a new visible practice problem using fresh numbers. Replaces the current exercise without answering it.',annotations:{readOnlyHint:false,untrustedContentHint:false},inputSchema:{type:'object',properties:{reactionId:{type:'integer',minimum:1,maximum:50},track:{type:'string',enum:['mass','limiting','percent']},balanceFirst:{type:'boolean'}},required:['reactionId','track','balanceFirst'],additionalProperties:false},execute:input=>{if(!input||!Number.isInteger(input.reactionId)||input.reactionId<1||input.reactionId>50||!['mass','limiting','percent'].includes(input.track)||typeof input.balanceFirst!=='boolean')throw Error('Choose a valid reaction, track and balancing option.');if(input.track==='limiting'&&REACTIONS[input.reactionId-1].reactants.length!==2)throw Error('This reaction has only one reactant. Choose mass or percent yield.');$('track').value=input.track;refreshReactions();$('reaction').value=String(input.reactionId);$('balance-mode').value=input.balanceFirst?'first':'given';newProblem();mode('practice');return {reactionId:problem.reaction.id,track:problem.track,ready:true};}}
 ];for(const tool of tools){try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}}window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
