import {REACTIONS} from './bank.js';
import {solve,molarMass,format} from './engine.js';
export const chem=f=>f.replace(/\d+/g,n=>`<sub>${n}</sub>`);
export const number=n=>format(n).replace(/ × 10\^(-?\d+)/,' × 10<sup>$1</sup>');
export const species=s=>`${chem(s.formula)}<span class="state">(${s.state})</span>`;
export function equation(r,balanced=true){const side=ss=>ss.map(s=>`<span class="species">${balanced&&s.coefficient!==1?s.coefficient+' ':''}${species(s)}</span>`).join('<span class="plus">+</span>');return `${side(r.reactants)}<span class="arrow" aria-label="yields">→</span>${side(r.products)}`;}
const fraction=(a,b)=>`<span class="fraction"><span>${a}</span><span>${b}</span></span>`;
export function calculation(p,path){const r=p.reaction.reactants[path.index],product=p.reaction.products[p.target];const a=chem(r.formula),b=chem(product.formula);return `<div class="calculation" aria-label="Mass to mass dimensional analysis"><span>${number(path.mass)} <span class="cancel">g ${a}</span></span><span>×</span>${fraction(`1 <span class="cancel">mol ${a}</span>`,`${molarMass(r.formula).toFixed(2)} <span class="cancel">g ${a}</span>`)}<span>×</span>${fraction(`${product.coefficient} <span class="cancel">mol ${b}</span>`,`${r.coefficient} <span class="cancel">mol ${a}</span>`)}<span>×</span>${fraction(`${molarMass(product.formula).toFixed(2)} g ${b}`,`1 <span class="cancel">mol ${b}</span>`)}<span>=</span><strong class="result-number">${number(path.yield)} g ${b}</strong></div>`;}
export function reference(p){const terms=[...p.given.map(g=>p.reaction.reactants[g.index]),p.reaction.products[p.target]];return `<aside class="reference"><h2>Molar masses</h2><dl>${terms.map(s=>`<div><dt>${chem(s.formula)}</dt><dd>${molarMass(s.formula).toFixed(2)} g/mol</dd></div>`).join('')}</dl><p class="muted context">Use these values for consistent answers.</p><details><summary>Keep your units</summary><p class="context">g reactant → mol reactant → mol product → g product</p><p class="context">Coefficients give the mole ratio. They do not give a mass ratio.</p></details></aside>`;}
export function solution(p){const s=solve(p),product=chem(p.reaction.products[p.target].formula);let html=`<h2>Worked solution</h2><p class="muted">Use the balanced equation. Retain extra digits until the final answer.</p><div class="equation">${equation(p.reaction)}</div>`;s.paths.forEach(path=>{html+=`<h3>From ${chem(p.reaction.reactants[path.index].formula)}</h3>${calculation(p,path)}`;});if(p.given.length===2)html+=`<p><strong>${chem(p.reaction.reactants[s.limiting].formula)} is limiting.</strong> It makes the smaller amount of ${product}. The smaller product yield is the theoretical yield.</p>`;html+=`<p><strong>Theoretical yield: ${number(s.theoretical)} g ${product}.</strong></p>`;if(p.actual!==null)html+=`<h3>Compare actual and theoretical yield</h3><div class="calculation">${fraction(`${number(p.actual)} g ${product}`,`${number(s.theoretical)} g ${product}`)}<span>× 100% =</span><strong class="result-number">${number(s.percent)}%</strong></div><p class="muted context">The displayed theoretical yield is rounded. The percent calculation retains the unrounded value.</p>`;return html;}
export function lessonView(track){const reaction=REACTIONS[0];const p={reaction,target:0,given:track==='limiting'?[{index:0,mass:10},{index:1,mass:5}]:[{index:0,mass:12}],actual:track==='percent'?17.5:null};const s=solve(p);const card=(prompt)=>`<div class="equation-card"><p class="eyebrow">${track==='mass'?'A BALANCED EQUATION IS YOUR RECIPE':track==='limiting'?'COMPARE WHAT EACH REACTANT CAN MAKE':'COMPARE WHAT YOU COLLECTED WITH WHAT YOU COULD MAKE'}</p><div class="equation">${equation(reaction)}</div><p>${prompt}</p></div>`;
 if(track==='mass')return card('What mass of MgO can form from <strong>12.0 g Mg</strong> with oxygen in excess?')+`<div class="mole-path"><div><small>START</small><strong>grams Mg</strong><span>÷ molar mass of Mg</span></div><div><small>CONVERT</small><strong>moles Mg</strong><span>× coefficient ratio</span></div><div><small>CONNECT</small><strong>moles MgO</strong><span>× molar mass of MgO</span></div><div><small>FINISH</small><strong>grams MgO</strong><span>Theoretical yield</span></div></div><div class="lesson-layout"><div><div class="lesson-copy"><h2>One continuous calculation</h2>${calculation(p,s.paths[0])}<p class="muted">The crossed-out units cancel, leaving grams of MgO.</p></div><ol class="step-list"><li><strong>Balance before you calculate.</strong><p>2 mol Mg produce 2 mol MgO. The coefficient ratio is 2/2.</p></li><li><strong>Convert grams of Mg to moles.</strong><p>12.0 ÷ 24.31 = 0.493624… mol Mg.</p></li><li><strong>Use the mole ratio.</strong><p>0.493624… × (2/2) = 0.493624… mol MgO.</p></li><li><strong>Convert moles of MgO to grams.</strong><p>0.493624… × 40.31 = 19.897984… g, or <strong>19.9 g MgO</strong> to three significant figures.</p></li></ol></div>${reference(p)}</div><div class="note"><strong>Why does the product weigh more?</strong><p>MgO contains the original magnesium plus oxygen from the other reactant. Mass is conserved across <em>all</em> reactants and products.</p></div>`;
 if(track==='limiting')return card('You have <strong>10.0 g Mg</strong> and <strong>5.00 g O<sub>2</sub></strong>. Which reactant runs out first, and what mass of MgO can form?')+`<div class="lesson-layout"><div><div class="lesson-copy"><h2>Run the same calculation twice.</h2><h3>From magnesium</h3>${calculation(p,s.paths[0])}<h3>From oxygen</h3>${calculation(p,s.paths[1])}</div><div class="compare"><div><small>Mg could make</small><strong>${number(s.paths[0].yield)} g MgO</strong></div><div class="limiting"><small>O<sub>2</sub> could make</small><strong>${number(s.paths[1].yield)} g MgO</strong><p>O<sub>2</sub> is limiting.</p></div></div><p><strong>The theoretical yield is ${number(s.theoretical)} g MgO.</strong> Once the oxygen is consumed, the reaction stops and some magnesium remains.</p></div>${reference(p)}</div><div class="note"><strong>Compare product yields, not starting masses.</strong><p>The smaller mass of reactant is not automatically limiting. Convert each reactant to the same product, then choose the smaller product yield.</p></div>`;
 return card('Starting with <strong>12.0 g Mg</strong> and excess oxygen, you collect <strong>17.5 g MgO</strong>. What is the percent yield?')+`<div class="lesson-layout"><div><div class="lesson-copy"><h2>1. Calculate the theoretical yield.</h2>${calculation(p,s.paths[0])}<h2>2. Compare the actual yield with it.</h2><p><strong>Actual yield</strong> is the amount collected: 17.5 g MgO.<br><strong>Theoretical yield</strong> is the calculated maximum: 19.897984… g MgO.</p><div class="calculation">${fraction('actual yield','theoretical yield')}<span>× 100%</span><span>=</span>${fraction('17.5 g MgO','19.897984… g MgO')}<span>× 100%</span><strong class="result-number">= ${number(s.percent)}%</strong></div><p>You collected about 88% of the amount predicted by the equation.</p></div></div>${reference(p)}</div><div class="note"><strong>Keep actual and theoretical yields separate.</strong><p>Use the reactants to calculate theoretical yield first. Both yields must refer to the same product in the same units. With two starting reactants, use the limiting reactant to determine theoretical yield.</p></div>`;
}
