import {REACTIONS} from './bank.js';
import {solve,molarMass,format} from './engine.js';
export const chem=f=>f.replace(/\d+/g,n=>`<sub>${n}</sub>`);
export const number=n=>format(n).replace(/ × 10\^(-?\d+)/,' × 10<sup>$1</sup>');
export const species=s=>`${chem(s.formula)}<span class="state">(${s.state})</span>`;
export function equation(r,balanced=true){const side=ss=>ss.map(s=>`<span class="species">${balanced&&s.coefficient!==1?s.coefficient+' ':''}${species(s)}</span>`).join('<span class="plus">+</span>');return `${side(r.reactants)}<span class="arrow" aria-label="yields">→</span>${side(r.products)}`;}
const fraction=(a,b)=>`<span class="fraction"><span>${a}</span><span>${b}</span></span>`;
export function calculation(p,path){const r=p.reaction.reactants[path.index],product=p.reaction.products[p.target];const a=chem(r.formula),b=chem(product.formula);return `<div class="calculation" aria-label="Mass to mass dimensional analysis"><span>${number(path.mass)} <span class="cancel">g ${a}</span></span><span>×</span>${fraction(`1 <span class="cancel">mol ${a}</span>`,`${molarMass(r.formula).toFixed(2)} <span class="cancel">g ${a}</span>`)}<span>×</span>${fraction(`${product.coefficient} <span class="cancel">mol ${b}</span>`,`${r.coefficient} <span class="cancel">mol ${a}</span>`)}<span>×</span>${fraction(`${molarMass(product.formula).toFixed(2)} g ${b}`,`1 <span class="cancel">mol ${b}</span>`)}<span>=</span><strong class="result-number">${number(path.yield)} g ${b}</strong></div>`;}
export function reference(p){const terms=[...p.given.map(g=>p.reaction.reactants[g.index]),p.reaction.products[p.target]];return `<aside class="reference"><h2>Molar masses</h2><dl>${terms.map(s=>`<div><dt>${chem(s.formula)}</dt><dd>${molarMass(s.formula).toFixed(2)} g/mol</dd></div>`).join('')}</dl><p class="muted context">Use these values for consistent answers.</p><details><summary>Keep your units</summary><p class="context">g reactant → mol reactant → mol product → g product</p><p class="context">Coefficients give the mole ratio. They do not give a mass ratio.</p></details></aside>`;}
export function solution(p){const s=solve(p),product=chem(p.reaction.products[p.target].formula);let html=`<h2>Worked solution</h2><p class="muted">Use the balanced equation. Retain extra digits until the final answer.</p><div class="equation">${equation(p.reaction)}</div>`;s.paths.forEach(path=>{html+=`<h3>From ${chem(p.reaction.reactants[path.index].formula)}</h3>${calculation(p,path)}`;});if(p.given.length===2)html+=`<p><strong>${chem(p.reaction.reactants[s.limiting].formula)} is limiting.</strong> It makes the smaller amount of ${product}. The smaller product yield is the theoretical yield.</p>`;html+=`<p><strong>Theoretical yield: ${number(s.theoretical)} g ${product}.</strong></p>`;if(p.actual!==null)html+=`<h3>Compare actual and theoretical yield</h3><div class="calculation">${fraction(`${number(p.actual)} g ${product}`,`${number(s.theoretical)} g ${product}`)}<span>× 100% =</span><strong class="result-number">${number(s.percent)}%</strong></div><p class="muted context">The displayed theoretical yield is rounded. The percent calculation retains the unrounded value.</p>`;return html;}
function sigFigGuide(track) {
 const example=track==='limiting'?'12.596875 g → <strong>12.6 g MgO</strong>':track==='percent'?'87.948606…% → <strong>87.9%</strong>':'19.897984… g → <strong>19.9 g MgO</strong>';
 const given=track==='limiting'?'10.0 g and 5.00 g each have three significant figures.':track==='percent'?'12.0 g and 17.5 g each have three significant figures.':'12.0 g has three significant figures: 1, 2, and the final 0.';
 return `<section class="precision-guide" aria-labelledby="precision-heading"><div><p class="eyebrow">FINISH WITH THE RIGHT PRECISION</p><h2 id="precision-heading">Carry extra digits. Round once.</h2><p>For multiplication and division, report the answer with the <strong>fewest significant figures among the measured values you use</strong>. ${given} The listed molar masses have at least that much precision, so report <strong>three significant figures</strong>.</p><p>Balanced coefficients are exact counts; they do not limit significant figures. The factor of 100 in percent yield is exact, too.</p></div><div class="rounding-example"><span>Calculator → reported answer</span><p>${example}</p><small>Keep the unrounded value in your calculator until the final answer${track==='percent'?'—including the theoretical yield in the denominator':''}.</small></div><details class="sigfig-details"><summary>Which zeros count?</summary><dl><div><dt>5.00</dt><dd>3 significant figures. Zeros after the decimal show measured precision.</dd></div><div><dt>0.00450</dt><dd>3 significant figures. Leading zeros only locate the decimal; the final zero counts.</dd></div><div><dt>19.90</dt><dd>4 significant figures. An extra zero claims extra precision.</dd></div><div><dt>1.20 × 10<sup>2</sup></dt><dd>3 significant figures. Scientific notation makes the precision clear when a whole number ends in zeros. Enter <code>1.20e2</code> in Practice.</dd></div></dl><p>Significant figures are not decimal places: 12.6 and 0.126 both have three significant figures.</p></details></section>`;
}

function massLesson(p,s,card) {
 return card('What mass of MgO can form from <strong>12.0 g Mg</strong> with oxygen in excess?')+`
 <p class="lesson-intro">“Oxygen in excess” means there is more than enough oxygen to react with all the magnesium. The amount of <strong>Mg</strong> determines how much MgO can form. Start with a balanced equation: 2 mol Mg make 2 mol MgO.</p>
 <figure class="conversion-map" aria-labelledby="conversion-caption"><figcaption id="conversion-caption"><span class="eyebrow">THREE CONVERSIONS · ONE ROUTE</span><strong>Grams → moles → moles → grams</strong></figcaption><ol class="conversion-route">
 <li><span class="route-role">WHAT YOU HAVE</span><strong>g Mg</strong><span>grams of reactant</span></li>
 <li class="route-link"><span>÷ molar mass of Mg</span><b aria-hidden="true">→</b><span class="route-step">1 · grams to moles</span></li>
 <li><span class="route-role">COUNT THE REACTANT</span><strong>mol Mg</strong><span>moles of reactant</span></li>
 <li class="route-link ratio-link"><span>× mole ratio</span><b aria-hidden="true">→</b><span class="route-step">2 · moles to moles</span></li>
 <li><span class="route-role">COUNT THE PRODUCT</span><strong>mol MgO</strong><span>moles of product</span></li>
 <li class="route-link"><span>× molar mass of MgO</span><b aria-hidden="true">→</b><span class="route-step">3 · moles to grams</span></li>
 <li class="route-finish"><span class="route-role">WHAT YOU WANT</span><strong>g MgO</strong><span>grams of product</span></li>
 </ol><p>Molar mass changes the <strong>unit</strong>. The mole ratio changes the <strong>substance</strong>.</p></figure>
 <div class="conversion-steps">
 <section class="conversion-step"><span class="step-badge">1</span><h2>Grams to moles</h2><p>Molar mass tells you the mass of one mole. Each mole of Mg has a mass of <strong>24.31 g</strong>, so divide your grams by 24.31 g/mol.</p><div class="calculation"><span>12.0 <span class="cancel">g Mg</span></span><span>×</span>${fraction('1 mol Mg','24.31 <span class="cancel">g Mg</span>')}<span>= 0.493624… mol Mg</span></div><p class="unit-explanation">Put g Mg on the bottom so it cancels the starting g Mg. Moles of Mg remain.</p></section>
 <section class="conversion-step ratio-step"><span class="step-badge">2</span><h2>Moles to moles</h2><p>The balanced equation is a recipe: <strong>2 mol Mg make 2 mol MgO</strong>. Put the coefficient of the substance you want on top; put the one you have on the bottom.</p><div class="calculation"><span>0.493624… <span class="cancel">mol Mg</span></span><span>×</span>${fraction('2 mol MgO','2 <span class="cancel">mol Mg</span>')}<span>= 0.493624… mol MgO</span></div><p class="unit-explanation">The ratio happens to be 1 here. With O<sub>2</sub> as the starting substance, it would be 2 mol MgO / 1 mol O<sub>2</sub>. Always read the coefficients.</p></section>
 <section class="conversion-step"><span class="step-badge">3</span><h2>Moles back to grams</h2><p>Each mole of MgO has a mass of <strong>40.31 g</strong>. Multiply by the <strong>product’s</strong> molar mass to find the mass of MgO.</p><div class="calculation"><span>0.493624… <span class="cancel">mol MgO</span></span><span>×</span>${fraction('40.31 g MgO','1 <span class="cancel">mol MgO</span>')}<span>= 19.897984… g MgO</span></div><p class="unit-explanation">Moles of MgO cancel. Grams of MgO remain—the unit the question asks for.</p></section>
 </div>
 <div class="lesson-copy"><h2>Now connect the three steps.</h2>${calculation(p,s.paths[0])}<p>The crossed-out units cancel, leaving <strong>19.9 g MgO</strong>, the theoretical yield. The intermediate decimals above are shortened for display; keep the full calculator value between steps.</p></div>
 ${sigFigGuide('mass')}
 <div class="note"><strong>Why does the product weigh more?</strong><p>MgO contains the original magnesium plus oxygen from the other reactant. Mass is conserved across <em>all</em> reactants and products. Coefficients compare moles, so applying 2/2 directly to 12.0 grams would not give the product’s mass.</p></div>`;
}

function limitingLesson(p,s,card) {
 const ratio=s.paths[1].yield/s.paths[0].yield*100;
 return card('You have <strong>10.0 g Mg</strong> and <strong>5.00 g O<sub>2</sub></strong>. Which reactant runs out first, and what mass of MgO can form?')+`
 <p class="lesson-intro">The <strong>limiting reactant</strong> is used up first. It sets the maximum amount of product. An <strong>excess reactant</strong> is left over when the limiting reactant is gone. With two given masses, do the grams → moles → moles → grams calculation <strong>twice</strong>.</p>
 <div class="lesson-copy"><p class="eyebrow">1 · ASK WHAT EACH REACTANT COULD MAKE</p><h2>Use the same product for both calculations.</h2><p>First imagine the other reactant is available in excess. Calculate the amount of MgO each starting amount could produce on its own.</p><section class="reactant-path"><h3>From 10.0 g Mg</h3><p>Divide by Mg’s molar mass → use 2 mol MgO / 2 mol Mg → multiply by MgO’s molar mass.</p>${calculation(p,s.paths[0])}<p class="muted">Before rounding: 16.581653… g MgO. This is Mg’s possible yield if enough oxygen is available.</p></section><section class="reactant-path"><h3>From 5.00 g O<sub>2</sub></h3><p>Divide by O<sub>2</sub>’s molar mass → use <strong>2 mol MgO / 1 mol O<sub>2</sub></strong> → multiply by MgO’s molar mass.</p>${calculation(p,s.paths[1])}<p class="muted">Before rounding: 12.596875 g MgO. Each mole of O<sub>2</sub> can make two moles of MgO, so this mole ratio is 2/1.</p></section></div>
 <figure class="yield-graphic" aria-labelledby="yield-caption"><figcaption id="yield-caption"><span class="eyebrow">2 · COMPARE THE POSSIBLE PRODUCT YIELDS</span><strong>The smaller product yield sets the limit.</strong></figcaption><div class="yield-row"><div><span>From 10.0 g Mg</span><strong>${number(s.paths[0].yield)} g MgO</strong></div><div class="yield-track" aria-hidden="true"><span style="width:100%"></span></div><p>Mg could make more, but there is not enough O<sub>2</sub> to do so.</p></div><div class="yield-row is-limiting"><div><span>From 5.00 g O<sub>2</sub></span><strong>${number(s.paths[1].yield)} g MgO · smaller yield</strong></div><div class="yield-track" aria-hidden="true"><span style="width:${ratio.toFixed(2)}%"></span></div><p>O<sub>2</sub> runs out first. This is the limiting reactant.</p></div><p class="context">Bar lengths compare unrounded yields; labels show three significant figures.</p></figure>
 <div class="limit-conclusion"><p class="eyebrow">3 · STATE BOTH PARTS OF THE ANSWER</p><h2>Limiting reactant: O<sub>2</sub></h2><p><strong>Theoretical yield: ${number(s.theoretical)} g MgO.</strong> Once all the oxygen has reacted, the reaction stops and some magnesium remains. Do not add or average the two possible yields: both calculations describe the same supply of product.</p></div>
 <details class="lesson-disclosure"><summary>Does the smaller starting mass always run out first?</summary><p><strong>No. Compare what the reactants can make, not their starting masses or raw mole counts.</strong> The reaction uses them in the ratio given by its coefficients.</p><p>For this same reaction, imagine <strong>1.00 g Mg</strong> and <strong>0.800 g O<sub>2</sub></strong>. Mg could make <strong>1.66 g MgO</strong>; O<sub>2</sub> could make <strong>2.02 g MgO</strong>. Mg is limiting even though its starting mass is larger.</p></details>
 ${sigFigGuide('limiting')}`;
}

export function lessonView(track) {
 const reaction=REACTIONS[0];
 const p={reaction,target:0,given:track==='limiting'?[{index:0,mass:10},{index:1,mass:5}]:[{index:0,mass:12}],actual:track==='percent'?17.5:null};
 const s=solve(p);
 const card=prompt=>`<div class="equation-card"><p class="eyebrow">${track==='mass'?'A BALANCED EQUATION IS YOUR RECIPE':track==='limiting'?'TWO STARTING AMOUNTS · ONE LIMIT':'COMPARE WHAT YOU COLLECTED WITH WHAT YOU COULD MAKE'}</p><div class="equation">${equation(reaction)}</div><p>${prompt}</p></div>`;
 if(track==='mass')return massLesson(p,s,card);
 if(track==='limiting')return limitingLesson(p,s,card);
 return card('Starting with <strong>12.0 g Mg</strong> and excess oxygen, you collect <strong>17.5 g MgO</strong>. What is the percent yield?')+`<div class="lesson-layout"><div><div class="lesson-copy"><h2>1. Calculate the theoretical yield.</h2>${calculation(p,s.paths[0])}<h2>2. Compare the actual yield with it.</h2><p><strong>Actual yield</strong> is the amount collected: 17.5 g MgO.<br><strong>Theoretical yield</strong> is the calculated maximum: 19.897984… g MgO.</p><div class="calculation">${fraction('actual yield','theoretical yield')}<span>× 100%</span><span>=</span>${fraction('17.5 g MgO','19.897984… g MgO')}<span>× 100%</span><strong class="result-number">= ${number(s.percent)}%</strong></div><p>You collected about 88% of the amount predicted by the equation. Keep the unrounded theoretical yield in the denominator; round the final percentage to <strong>87.9%</strong>.</p></div></div>${reference(p)}</div>${sigFigGuide('percent')}<div class="note"><strong>Keep actual and theoretical yields separate.</strong><p>Use the reactants to calculate theoretical yield first. Both yields must refer to the same product in the same units. With two starting reactants, use the limiting reactant to determine theoretical yield.</p></div>`;
}
